"use client";
import { useMemo,useState } from "react";
import type { CenterlineResult } from "./centerline";
import type { MachinePlan } from "./machine-plan";
import { assessEmbroideryDetails } from "./detail-intelligence";
type PreviewMode="artwork"|"centerline"|"cleaned"|"stitches"|"route";type StitchMode="running"|"bean";type Props={source:string;imageUrl:string;alt:string;centerlineResult:CenterlineResult|null;machinePlan:MachinePlan|null;busy:boolean;stitchMode?:StitchMode};
function readViewBox(source:string){const p=new DOMParser().parseFromString(source,"image/svg+xml"),s=p.documentElement,r=s.getAttribute("viewBox")?.trim().split(/[\s,]+/).map(Number);if(r?.length===4&&r.every(Number.isFinite))return r as [number,number,number,number];const w=Number.parseFloat(s.getAttribute("width")??"")||1,h=Number.parseFloat(s.getAttribute("height")??"")||w;return[0,0,w,h] as [number,number,number,number]}
const attr=(p:{x:number;y:number}[])=>p.map(x=>`${x.x},${x.y}`).join(" ");function bean(p:{x:number;y:number}[]){if(p.length<2)return p;const r=[p[0]];for(let i=1;i<p.length;i++)r.push(p[i],p[i-1],p[i]);return r}
export default function StitchPreview({source,imageUrl,alt,centerlineResult,machinePlan,busy,stitchMode="running"}:Props){const[mode,setMode]=useState<PreviewMode>("artwork"),[minX,minY,width,height]=useMemo(()=>readViewBox(source),[source]),paths=centerlineResult?.paths??[],route=machinePlan?.paths??[],intel=useMemo(()=>assessEmbroideryDetails(centerlineResult),[centerlineResult]),show=mode!=="artwork"&&paths.length>0,stitches=mode==="stitches",machine=mode==="route",cleaned=mode==="cleaned";return <div style={{position:"relative",width:"100%",height:230}}><img src={imageUrl} alt={alt} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"contain",opacity:mode==="artwork"?1:.16}}/>{show&&<svg viewBox={`${minX} ${minY} ${width} ${height}`} preserveAspectRatio="xMidYMid meet" style={{position:"absolute",inset:0,width:"100%",height:"100%"}}>{(machine?route:paths).map((path,index)=>{const decision=intel?.details[index]?.decision??"keep";if(cleaned&&decision==="remove")return null;const base=stitches||machine?path.stitches:path.points,rendered=stitches&&stitchMode==="bean"?bean(base):base;return <polyline key={index} points={attr(rendered)} fill="none" stroke={cleaned?(decision==="simplify"?"#d98245":"#52624b"):(stitches||machine?"#1e211d":"#e85d34")} strokeWidth={Math.max(width/750,.35)} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" opacity={.88}/>})}{stitches&&paths.flatMap((p,i)=>(stitchMode==="bean"?bean(p.stitches):p.stitches).map((x,j)=><circle key={`${i}-${j}`} cx={x.x} cy={x.y} r={Math.max(width/430,.65)} fill="#e85d34"/>))}{machine&&machinePlan?.bridges.map((b,i)=><line key={`b${i}`} x1={b.from.x} y1={b.from.y} x2={b.to.x} y2={b.to.y} stroke="#6f8066" strokeWidth={1.15}/>)}{machine&&machinePlan?.jumps.map((j,i)=><line key={`j${i}`} x1={j.from.x} y1={j.from.y} x2={j.to.x} y2={j.to.y} stroke={j.trim?"#e85d34":"#7d8079"} strokeWidth={j.trim?1.15:.85} strokeDasharray={j.trim?"5 3":"2 3"}/>)}</svg>}<div role="group" aria-label="Preview mode" style={{position:"absolute",left:0,top:-20,display:"flex",gap:4,padding:4,border:"1px solid rgba(30,33,29,.16)",borderRadius:5,background:"rgba(247,242,231,.9)",zIndex:2}}>{(["artwork","centerline","cleaned","stitches","route"] as PreviewMode[]).map(o=>{const active=mode===o,disabled=o!=="artwork"&&(busy||!paths.length||(o==="route"&&!machinePlan));return <button key={o} disabled={disabled} onClick={()=>setMode(o)} style={{border:0,borderRadius:3,padding:"7px 9px",color:active?"#f7f2e7":"rgba(30,33,29,.62)",background:active?"#1e211d":"transparent",font:"9px var(--font-geist-mono)",letterSpacing:".07em",textTransform:"uppercase",opacity:disabled?.35:1}}>{o}</button>})}</div>{cleaned&&intel&&<div style={{position:"absolute",right:0,bottom:-18,font:"9px var(--font-geist-mono)",letterSpacing:".05em",textTransform:"uppercase",color:"rgba(30,33,29,.62)"}}>{intel.keep} keep · {intel.simplify} simplify · {intel.remove} remove</div>}</div>}
